/*Creamos la fase inicial en donde encontraremos la fase inicial con todos los paisees encuadrados en  los grupos*/
CREATE TABLE FASE1(
    GRUPO VARCHAR(100) PRIMARY KEY,
    PAIS1 VARCHAR(9) NOT NULL ,
    PAIS2 VARCHAR(10) NOT NULL ,
     PAIS3 VARCHAR(7) NOT NULL ,
     PAIS4 VARCHAR(15) NOT NULL ,
     PAIS5 VARCHAR(8) NOT NULL ,
     PAIS6 VARCHAR(20) NOT NULL

);
INSERT INTO FASE1 (GRUPO, PAIS1, PAIS2, PAIS3, PAIS4, PAIS5, PAIS6) VALUES
                                        ('A','ESPANA','MONTENEGRO','TURQUIA','GEORGIA','BELGICA','BULGARIA'),
                                        ('B','ESLOVENIA','ALEMANIA','FRANCIA','LITUANIA','HUNGRIA','BOSNIA Y HERZEGOVINA'),
                                        ('C','GRECIA','UCRANIA','CROACIA','ITALIA','ESTONIA','GRAN BRETANA'),
                                        ('D','SERBIA','FINLANDIA','POLONIA','REPUBLICA CHECA','ISRAEL','PAISES BAJOS');
SELECT * FROM FASE1;

CREATE TABLE OCTAVOS(
     GRUPO VARCHAR(100) PRIMARY KEY,
     PAIS1 VARCHAR(9) NOT NULL ,
     PAIS2 VARCHAR(10) NOT NULL ,
     PAIS3 VARCHAR(7) NOT NULL ,
     PAIS4 VARCHAR(15) NOT NULL ,
     PAIS5 VARCHAR(8) NOT NULL ,
     PAIS6 VARCHAR(20) NOT NULL,
     PAIS7 VARCHAR(7) NOT NULL ,
     PAIS8 VARCHAR(15) NOT NULL ,
     PAIS9 VARCHAR(8) NOT NULL ,
     PAIS10 VARCHAR(20) NOT NULL,
     PAIS11 VARCHAR(7) NOT NULL ,
     PAIS12 VARCHAR(15) NOT NULL ,
     PAIS13 VARCHAR(8) NOT NULL ,
     PAIS14 VARCHAR(20) NOT NULL,
     PAIS15 VARCHAR(7) NOT NULL ,
     PAIS16 VARCHAR(15) NOT NULL
);
/*AÑADIMOS LOS VALORES ABAJO*/

/*CREAMOS LA TABLA DE CUARTOS DE FINAL*/
CREATE TABLE CUARTOS(
     GRUPO VARCHAR(100) PRIMARY KEY,
     PAIS1 VARCHAR(9) NOT NULL ,
     PAIS2 VARCHAR(10) NOT NULL ,
     PAIS3 VARCHAR(7) NOT NULL ,
     PAIS4 VARCHAR(15) NOT NULL ,
     PAIS5 VARCHAR(8) NOT NULL ,
     PAIS6 VARCHAR(20) NOT NULL,
     PAIS7 VARCHAR(7) NOT NULL ,
     PAIS8 VARCHAR(15) NOT NULL
);
/*AÑADIMOS LOS VALORES ABAJO*/


/*CREAMOS LA TABLA DE SEMIFINAL*/
CREATE TABLE SEMIFINAL(
     GRUPO VARCHAR(100) PRIMARY KEY,
     PAIS1 VARCHAR(9) NOT NULL ,
     PAIS2 VARCHAR(10) NOT NULL ,
     PAIS3 VARCHAR(7) NOT NULL ,
     PAIS4 VARCHAR(15) NOT NULL
);
/*AÑADIMOS LOS VALORES ABAJO*/


/*CREAMOS LA TABLA DE FINAL*/
CREATE TABLE FINAL(
     GRUPO VARCHAR(100) PRIMARY KEY,
     PAIS1 VARCHAR(9) NOT NULL ,
     PAIS2 VARCHAR(10) NOT NULL
);
/*AÑADIMOS LOS VALORES ABAJO*/



