
CREATE TABLE FASE1(
    grupo VARCHAR(100) PRIMARY KEY,
    pais VARCHAR(100) NOT NULL ,
    PAIS2 VARCHAR(100) NOT NULL ,
     PAIS3 VARCHAR(100) NOT NULL ,
     PAIS4 VARCHAR(100) NOT NULL ,
     PAIS5 VARCHAR(100) NOT NULL ,
     PAIS6 VARCHAR(100) NOT NULL

);
INSERT INTO FASE1 (GRUPO, PAIS, PAIS2, PAIS3, PAIS4, PAIS5, PAIS6) VALUES
                                        ('A','ESPANA','MONTENEGRO','TURQUIA','GEORGIA','BELGICA','BULGARIA'),
                                        ('B','ESPANA','MONTENEGRO','TURQUIA','GEORGIA','BELGICA','BULGARIA'),
                                        ('C','ESPANA','MONTENEGRO','TURQUIA','GEORGIA','BELGICA','BULGARIA'),
                                        ('D','ESPANA','MONTENEGRO','TURQUIA','GEORGIA','BELGICA','BULGARIA');
SELECT * FROM FASE1;









