

CREATE TABLE GRUPOS(
  grupo VARCHAR(1) CONSTRAINT grupos_pk PRIMARY KEY,
  pais VARCHAR (21) CONSTRAINT grupos_nn1 NOT NULL
                    CONSTRAINT grupos_uk UNIQUE
);
CREATE TABLE FASES(
    grupo VARCHAR(1) CONSTRAINT fases_nn1 NOT NULL,
    fase VARCHAR(11) CONSTRAINT fases_pk PRIMARY KEY,
    pais VARCHAR(21) CONSTRAINT fases_nn2 NOT NULL
);




